'use client'

import React from 'react'
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'

const styles = StyleSheet.create({
  page: {
    padding: 35,
    fontSize: 9,
    fontFamily: 'Helvetica',
    color: '#1E293B',
    backgroundColor: '#FFFFFF',
  },
  headerBanner: {
    marginBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: '#4F46E5',
    paddingBottom: 12,
  },
  logoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  brandTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#4F46E5',
    letterSpacing: 0.5,
  },
  reportSubtitle: {
    fontSize: 10,
    color: '#64748B',
    marginTop: 2,
  },
  metaBadge: {
    fontSize: 8,
    color: '#4F46E5',
    backgroundColor: '#EEF2FF',
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 4,
  },
  metaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 6,
    fontSize: 8,
    color: '#64748B',
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#0F172A',
    marginBottom: 8,
    marginTop: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    paddingBottom: 4,
  },
  kpiGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 14,
  },
  kpiCard: {
    flexBasis: '31%',
    backgroundColor: '#F8FAFC',
    borderRadius: 6,
    padding: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  kpiValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1E293B',
    marginBottom: 2,
  },
  kpiLabel: {
    fontSize: 7.5,
    color: '#64748B',
    textTransform: 'uppercase',
  },
  table: {
    width: '100%',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 4,
    overflow: 'hidden',
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#F1F5F9',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    paddingVertical: 5,
    paddingHorizontal: 8,
  },
  tableRowAlt: {
    backgroundColor: '#FAFAFA',
  },
  colHeader: {
    fontSize: 8,
    fontWeight: 'bold',
    color: '#475569',
  },
  colCell: {
    fontSize: 8,
    color: '#334155',
  },
  footer: {
    position: 'absolute',
    bottom: 25,
    left: 35,
    right: 35,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    paddingTop: 8,
    fontSize: 7.5,
    color: '#94A3B8',
  },
})

interface IndividualReportPdfProps {
  data: any
  generatedByName?: string
}

export function IndividualReportDocument({ data, generatedByName }: IndividualReportPdfProps) {
  const {
    workspaceName,
    memberName,
    memberRole,
    rangeFrom,
    rangeTo,
    generatedAt,
    summary,
    completedList = [],
    overdueList = [],
    inProgressList = [],
  } = data || {}

  const formattedGenDate = generatedAt ? new Date(generatedAt).toLocaleString() : new Date().toLocaleString()

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Banner */}
        <View style={styles.headerBanner}>
          <View style={styles.logoRow}>
            <View>
              <Text style={styles.brandTitle}>SprintDesk</Text>
              <Text style={styles.reportSubtitle}>Individual Performance & Task Report</Text>
            </View>
            <Text style={styles.metaBadge}>INDIVIDUAL REPORT</Text>
          </View>
          <View style={styles.metaRow}>
            <Text>Member: {memberName} ({memberRole})</Text>
            <Text>Workspace: {workspaceName}</Text>
            <Text>Period: {rangeFrom} to {rangeTo}</Text>
          </View>
          {generatedByName && (
            <View style={[styles.metaRow, { marginTop: 3 }]}>
              <Text>Generated by: {generatedByName}</Text>
              <Text>Generated on: {formattedGenDate}</Text>
            </View>
          )}
        </View>

        {/* Section 1: Summary KPI Cards */}
        <Text style={styles.sectionTitle}>Performance Overview</Text>
        <View style={styles.kpiGrid}>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiValue}>{summary?.tasksAssigned || 0}</Text>
            <Text style={styles.kpiLabel}>Tasks Assigned</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={[styles.kpiValue, { color: '#8B5CF6' }]}>{summary?.totalHoursLogged || '0h 0m'}</Text>
            <Text style={styles.kpiLabel}>Hours Tracked</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={[styles.kpiValue, { color: '#16A34A' }]}>{summary?.tasksCompleted || 0}</Text>
            <Text style={styles.kpiLabel}>Tasks Completed</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={[styles.kpiValue, { color: '#4F46E5' }]}>{summary?.completionRate || 0}%</Text>
            <Text style={styles.kpiLabel}>Completion Rate</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={[styles.kpiValue, { color: '#DC2626' }]}>{summary?.overdueCount || 0}</Text>
            <Text style={styles.kpiLabel}>Overdue Tasks</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={[styles.kpiValue, { color: '#2563EB' }]}>{summary?.inProgressCount || 0}</Text>
            <Text style={styles.kpiLabel}>In Progress</Text>
          </View>
        </View>

        {/* Section 2: Completed Tasks */}
        <Text style={styles.sectionTitle}>Completed Tasks in Period ({completedList.length})</Text>
        <View style={styles.table}>
          <View style={styles.tableHeader}>
            <Text style={[styles.colHeader, { flex: 4.5 }]}>Task Title</Text>
            <Text style={[styles.colHeader, { flex: 1.5, textAlign: 'center' }]}>Priority</Text>
            <Text style={[styles.colHeader, { flex: 2, textAlign: 'center' }]}>Time Spent</Text>
            <Text style={[styles.colHeader, { flex: 2, textAlign: 'right' }]}>Completed Date</Text>
          </View>
          {completedList.length === 0 ? (
            <View style={styles.tableRow}>
              <Text style={[styles.colCell, { flex: 1, textAlign: 'center', color: '#94A3B8' }]}>
                No tasks completed within this date range.
              </Text>
            </View>
          ) : (
            completedList.slice(0, 10).map((t: any, idx: number) => (
              <View key={idx} style={[styles.tableRow, idx % 2 === 1 ? styles.tableRowAlt : {}]}>
                <Text style={[styles.colCell, { flex: 4.5 }]}>{t.title}</Text>
                <Text style={[styles.colCell, { flex: 1.5, textAlign: 'center', textTransform: 'capitalize' }]}>
                  {t.priority}
                </Text>
                <Text style={[styles.colCell, { flex: 2, textAlign: 'center', color: '#8B5CF6' }]}>
                  {t.actual_duration || '-'}
                </Text>
                <Text style={[styles.colCell, { flex: 2, textAlign: 'right', color: '#64748B' }]}>
                  {t.completed_at ? new Date(t.completed_at).toISOString().split('T')[0] : '-'}
                </Text>
              </View>
            ))
          )}
        </View>

        {/* Section 3: Overdue Tasks */}
        {overdueList.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Overdue Tasks Requiring Action ({overdueList.length})</Text>
            <View style={styles.table}>
              <View style={styles.tableHeader}>
                <Text style={[styles.colHeader, { flex: 5 }]}>Task Title</Text>
                <Text style={[styles.colHeader, { flex: 1.5, textAlign: 'center' }]}>Priority</Text>
                <Text style={[styles.colHeader, { flex: 2.5, textAlign: 'right' }]}>Due Date</Text>
                <Text style={[styles.colHeader, { flex: 1.5, textAlign: 'right' }]}>Days Overdue</Text>
              </View>
              {overdueList.slice(0, 8).map((t: any, idx: number) => (
                <View key={idx} style={[styles.tableRow, idx % 2 === 1 ? styles.tableRowAlt : {}]}>
                  <Text style={[styles.colCell, { flex: 5 }]}>{t.title}</Text>
                  <Text style={[styles.colCell, { flex: 1.5, textAlign: 'center', textTransform: 'capitalize' }]}>
                    {t.priority}
                  </Text>
                  <Text style={[styles.colCell, { flex: 2.5, textAlign: 'right' }]}>
                    {t.due_date ? new Date(t.due_date).toISOString().split('T')[0] : '-'}
                  </Text>
                  <Text style={[styles.colCell, { flex: 1.5, textAlign: 'right', color: '#DC2626', fontWeight: 'bold' }]}>
                    {t.days_overdue}d
                  </Text>
                </View>
              ))}
            </View>
          </>
        )}

        {/* Section 4: Current In-Progress */}
        {inProgressList.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Active In-Progress Tasks ({inProgressList.length})</Text>
            <View style={styles.table}>
              <View style={styles.tableHeader}>
                <Text style={[styles.colHeader, { flex: 6 }]}>Task Title</Text>
                <Text style={[styles.colHeader, { flex: 1.5, textAlign: 'center' }]}>Priority</Text>
                <Text style={[styles.colHeader, { flex: 2.5, textAlign: 'right' }]}>Status</Text>
              </View>
              {inProgressList.slice(0, 8).map((t: any, idx: number) => (
                <View key={idx} style={[styles.tableRow, idx % 2 === 1 ? styles.tableRowAlt : {}]}>
                  <Text style={[styles.colCell, { flex: 6 }]}>{t.title}</Text>
                  <Text style={[styles.colCell, { flex: 1.5, textAlign: 'center', textTransform: 'capitalize' }]}>
                    {t.priority}
                  </Text>
                  <Text style={[styles.colCell, { flex: 2.5, textAlign: 'right', textTransform: 'capitalize' }]}>
                    {t.status.replace('_', ' ')}
                  </Text>
                </View>
              ))}
            </View>
          </>
        )}

        {/* Footer */}
        <View style={styles.footer}>
          <Text>SprintDesk · Member Performance Record</Text>
          <Text>Generated on {formattedGenDate}</Text>
        </View>
      </Page>
    </Document>
  )
}
