'use client'

import React from 'react'
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'

const styles = StyleSheet.create({
  page: {
    padding: 35,
    fontSize: 9,
    fontFamily: 'Helvetica',
    color: '#1E293B',
    backgroundColor: '#FFFFFF',
  },
  headerBanner: {
    marginBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: '#4F46E5',
    paddingBottom: 12,
  },
  logoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  brandTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#4F46E5',
    letterSpacing: 0.5,
  },
  reportSubtitle: {
    fontSize: 10,
    color: '#64748B',
    marginTop: 2,
  },
  metaBadge: {
    fontSize: 8,
    color: '#4F46E5',
    backgroundColor: '#EEF2FF',
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 4,
  },
  metaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 6,
    fontSize: 8,
    color: '#64748B',
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#0F172A',
    marginBottom: 8,
    marginTop: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    paddingBottom: 4,
  },
  kpiGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 14,
  },
  kpiCard: {
    flexBasis: '31%',
    backgroundColor: '#F8FAFC',
    borderRadius: 6,
    padding: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  kpiValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1E293B',
    marginBottom: 2,
  },
  kpiLabel: {
    fontSize: 7.5,
    color: '#64748B',
    textTransform: 'uppercase',
  },
  table: {
    width: '100%',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 4,
    overflow: 'hidden',
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#F1F5F9',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    paddingVertical: 5,
    paddingHorizontal: 8,
  },
  tableRowAlt: {
    backgroundColor: '#FAFAFA',
  },
  colHeader: {
    fontSize: 8,
    fontWeight: 'bold',
    color: '#475569',
  },
  colCell: {
    fontSize: 8,
    color: '#334155',
  },
  footer: {
    position: 'absolute',
    bottom: 25,
    left: 35,
    right: 35,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    paddingTop: 8,
    fontSize: 7.5,
    color: '#94A3B8',
  },
})

interface TeamReportPdfProps {
  data: any
  generatedByName: string
}

export function TeamReportDocument({ data, generatedByName }: TeamReportPdfProps) {
  const {
    workspaceName,
    rangeFrom,
    rangeTo,
    generatedAt,
    summary,
    memberWorkload = [],
    overdueTasks = [],
    completedTasksList = [],
    upcomingTasksList = [],
  } = data || {}

  const formattedGenDate = generatedAt ? new Date(generatedAt).toLocaleString() : new Date().toLocaleString()

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Banner */}
        <View style={styles.headerBanner}>
          <View style={styles.logoRow}>
            <View>
              <Text style={styles.brandTitle}>SprintDesk</Text>
              <Text style={styles.reportSubtitle}>Workspace Team Performance Report</Text>
            </View>
            <Text style={styles.metaBadge}>PRO REPORT</Text>
          </View>
          <View style={styles.metaRow}>
            <Text>Workspace: {workspaceName}</Text>
            <Text>Period: {rangeFrom} to {rangeTo}</Text>
            <Text>Generated by: {generatedByName}</Text>
          </View>
        </View>

        {/* Section 1: Executive KPI Cards */}
        <Text style={styles.sectionTitle}>Executive Summary</Text>
        <View style={styles.kpiGrid}>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiValue}>{summary?.totalTasks || 0}</Text>
            <Text style={styles.kpiLabel}>Total Tasks</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={[styles.kpiValue, { color: '#8B5CF6' }]}>{summary?.totalTeamHours || '0h 0m'}</Text>
            <Text style={styles.kpiLabel}>Hours Tracked</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={[styles.kpiValue, { color: '#16A34A' }]}>{summary?.completedCount || 0}</Text>
            <Text style={styles.kpiLabel}>Completed</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={[styles.kpiValue, { color: '#4F46E5' }]}>{summary?.completionRate || 0}%</Text>
            <Text style={styles.kpiLabel}>Completion Rate</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={[styles.kpiValue, { color: '#DC2626' }]}>{summary?.overdueCount || 0}</Text>
            <Text style={styles.kpiLabel}>Overdue</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={[styles.kpiValue, { color: '#2563EB' }]}>{summary?.inProgressCount || 0}</Text>
            <Text style={styles.kpiLabel}>In Progress</Text>
          </View>
        </View>

        {/* Section 2: Team Member Workload */}
        <Text style={styles.sectionTitle}>Team Workload & Hours</Text>
        <View style={styles.table}>
          <View style={styles.tableHeader}>
            <Text style={[styles.colHeader, { flex: 3 }]}>Member</Text>
            <Text style={[styles.colHeader, { flex: 1.2, textAlign: 'center' }]}>Assigned</Text>
            <Text style={[styles.colHeader, { flex: 1.2, textAlign: 'center' }]}>Completed</Text>
            <Text style={[styles.colHeader, { flex: 1.5, textAlign: 'center' }]}>Hours</Text>
            <Text style={[styles.colHeader, { flex: 1.2, textAlign: 'center' }]}>Overdue</Text>
            <Text style={[styles.colHeader, { flex: 1.5, textAlign: 'right' }]}>Rate</Text>
          </View>
          {memberWorkload.length === 0 ? (
            <View style={styles.tableRow}>
              <Text style={[styles.colCell, { flex: 1, textAlign: 'center', color: '#94A3B8' }]}>
                No member workload records in this period.
              </Text>
            </View>
          ) : (
            memberWorkload.slice(0, 10).map((m: any, idx: number) => (
              <View key={idx} style={[styles.tableRow, idx % 2 === 1 ? styles.tableRowAlt : {}]}>
                <Text style={[styles.colCell, { flex: 3, fontWeight: 'medium' }]}>{m.member_name}</Text>
                <Text style={[styles.colCell, { flex: 1.2, textAlign: 'center' }]}>{m.assigned}</Text>
                <Text style={[styles.colCell, { flex: 1.2, textAlign: 'center', color: '#16A34A' }]}>{m.completed}</Text>
                <Text style={[styles.colCell, { flex: 1.5, textAlign: 'center', color: '#8B5CF6' }]}>{m.hours_logged || '0h 0m'}</Text>
                <Text style={[styles.colCell, { flex: 1.2, textAlign: 'center', color: m.overdue > 0 ? '#DC2626' : '#64748B' }]}>
                  {m.overdue}
                </Text>
                <Text style={[styles.colCell, { flex: 1.5, textAlign: 'right', fontWeight: 'bold' }]}>
                  {m.completion_rate}%
                </Text>
              </View>
            ))
          )}
        </View>

        {/* Section 3: Critical Overdue Tasks */}
        {overdueTasks.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Attention Required: Overdue Tasks</Text>
            <View style={styles.table}>
              <View style={styles.tableHeader}>
                <Text style={[styles.colHeader, { flex: 4 }]}>Task Title</Text>
                <Text style={[styles.colHeader, { flex: 2.5 }]}>Assigned To</Text>
                <Text style={[styles.colHeader, { flex: 1.5, textAlign: 'center' }]}>Priority</Text>
                <Text style={[styles.colHeader, { flex: 2, textAlign: 'right' }]}>Overdue By</Text>
              </View>
              {overdueTasks.slice(0, 8).map((task: any, idx: number) => (
                <View key={idx} style={[styles.tableRow, idx % 2 === 1 ? styles.tableRowAlt : {}]}>
                  <Text style={[styles.colCell, { flex: 4 }]}>{task.title}</Text>
                  <Text style={[styles.colCell, { flex: 2.5 }]}>{task.assigned_to_name}</Text>
                  <Text style={[styles.colCell, { flex: 1.5, textAlign: 'center', textTransform: 'capitalize' }]}>
                    {task.priority}
                  </Text>
                  <Text style={[styles.colCell, { flex: 2, textAlign: 'right', color: '#DC2626', fontWeight: 'bold' }]}>
                    {task.days_overdue} days
                  </Text>
                </View>
              ))}
            </View>
          </>
        )}

        {/* Section 4: Completed Tasks Overview */}
        {completedTasksList.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Recently Completed Tasks ({completedTasksList.length})</Text>
            <View style={styles.table}>
              <View style={styles.tableHeader}>
                <Text style={[styles.colHeader, { flex: 4.5 }]}>Task Title</Text>
                <Text style={[styles.colHeader, { flex: 2.5 }]}>Completed By</Text>
                <Text style={[styles.colHeader, { flex: 2, textAlign: 'right' }]}>Date</Text>
              </View>
              {completedTasksList.slice(0, 8).map((task: any, idx: number) => (
                <View key={idx} style={[styles.tableRow, idx % 2 === 1 ? styles.tableRowAlt : {}]}>
                  <Text style={[styles.colCell, { flex: 4.5 }]}>{task.title}</Text>
                  <Text style={[styles.colCell, { flex: 2.5 }]}>{task.assigned_to_name}</Text>
                  <Text style={[styles.colCell, { flex: 2, textAlign: 'right' }]}>
                    {task.completed_at ? new Date(task.completed_at).toISOString().split('T')[0] : '-'}
                  </Text>
                </View>
              ))}
            </View>
          </>
        )}

        {/* Footer */}
        <View style={styles.footer}>
          <Text>SprintDesk · Generated on {formattedGenDate}</Text>
          <Text>Confidential Workspace Document</Text>
        </View>
      </Page>
    </Document>
  )
}
